config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "pages#main"

    resources :events, only: [:show] do
      resources :event_attendees, only: [:create, :delete]
    end
    

    resources :users, only: [:show] do
        resources :events, except: [:show]
    end


    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events_created, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
  has_many :event_attendees, foreign_key: "attendee_id", dependent: :destroy
  has_many :attended_events, through: :event_attendees, source: :event, dependent: :destroy

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:index]
  def show
    @user = User.find(params[:id])
   
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_event-preview.html.erb
<% list_of_events.each do |event|%>

    <div class= "custom-card-main__index">

            <div class="custom-card-main__left">

                <div class="custom-card-main__title--small">
                    <%= link_to event.name, event_path(event.id)%>
                </div>
                <div class="custom-card-main__stats">
                    <div class= "custom-card-main__stats__item">
                        <%= event.created_at.strftime('%Y-%m-%d') %>
                    </div>
                    <div class= "custom-card-main__stats__item">
                        <%= event.date%>
                    </div>
                
                </div>
            </div>

         
       <div class="custom-card-main__right">
        <div class="custom-card-main__actions">
            <%= link_to edit_user_event_path(current_user.id, event.id) do %>

                <%= image_tag("edit_pencil.svg") %>
            <% end %>
        
            <%= link_to user_event_path(current_user.id, event.id), 
                data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" } do %>
                <%= image_tag("delete_trash.svg") %>
            <% end %>
        </div>
       </div>

</div>

<% end %>

app/views/users/_visitor-event-preview.html.erb
<% list_of_events.each do |event|%>

    <div class= "custom-card-main__index">

            <div class="custom-card-main__left">

                <div class="custom-card-main__title--small">
                    <%= link_to event.name, event_path(event.id)%>
                </div>
                <div class="custom-card-main__stats">
                    <div class= "custom-card-main__stats__item">
                        <%= event.created_at.strftime('%Y-%m-%d') %>
                    </div>
                    <div class= "custom-card-main__stats__item">
                        <%= event.date%>
                    </div>
                
                </div>
            </div>

         
</div>

<% end %>

app/views/users/show.html.erb
<div class="container-fluid w-50 mt-5">


<% if current_user && @user.id == current_user.id %>
    <h1 class="text-center mb-5"> Your events </h1>
<% else %>
    <h1 class="text-center mb-5"> <%= @user.user_name %> events </h1>
<% end %>
      

    
    <div class="container custom-main-cards-container">
        <% if current_user && @user.id == current_user.id %>
             <%= render partial: "event-preview", locals: {list_of_events: @user.events_created} %> <br>
            <% else %>
             <%= render partial: "visitor-event-preview", locals: {list_of_events: @user.events_created} %> <br>
        <% end %>    
    </div>
    

    <div class="container">
    
        <div class="custom-main-cards-container">
            <div class="container">
                <h5>Events attended</h5>


                <%= render partial: "shared/event-preview-small", locals:{list_of_events:@user.attended_events.past_events}%>


            </div>



        </div>
         <div class="custom-main-cards-container">
            <div class="container">
                <h5>Upcoming Events</h5>
                 <%= render partial: "shared/event-preview-small", locals:{list_of_events: @user.attended_events.upcoming_events}%>
            </div>


        </div>
    </div>



</div>