config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "pages#main"

    resources :events, only: [:show] do
      resources :event_attendees, only: [:create, :delete]
    end
    

    resources :users, only: [:show] do
        resources :events, except: [:show]
    end


    

end

app/views/shared/_event-preview-small.html.erb
<% list_of_events.each do |event|%>
    <div class= "custom-card-main ">


        <div class="custom-card-main__title--small"> 
            <%= link_to event.name, event_path(event.id)%> 
        </div>

        <div class="custom-card-main__stats">
            <div class= "custom-card-main__stats__item"> 
               Date: <%= event.date%> 
            </div>             
        </div>

    <div class="custom-card-main__body"> 
        <%= truncate(event.description, length: 100)%>
    </div>


</div>
<% end %>

app/views/shared/_event-preview.html.erb
<% list_of_events.each do |event| %>

  <div class="custom-card-main">

    <div class="custom-card-main__title">
      <%= link_to event.name, event_path(event.id) %>
    </div>

    <div class="custom-card-main__stats">
      <div class="custom-card-main__stats__item">
        Created at: <%= event.created_at.strftime('%Y-%m-%d') %>
      </div>
      <div class="custom-card-main__stats__item">
        Event Date: <%= event.date %>
      </div>
      <div class="custom-card-main__stats__item">
       Creator: <%= event.creator.user_name %>
      </div>
    </div>


    <div class="custom-card-main__body"> 
        <%= truncate(event.description, length: 250)%>
        </div>

  </div>

<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
   <div class="container-fluid d-flex justify-content-center">
   
    <span class="navbar-brand mb-0 h1">The Odin Project</span>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Event Buddy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_user%>
            <div class="dropdown">
              <a class="btn btn-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Events
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Event", new_user_event_path(current_user), class: "nav-link"%></li>
                <li><%= link_to "Your Events", user_path(current_user), class: "nav-link"%></li>
              </ul>
            </div>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">

        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-light mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>