config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    root to: "pages#main"

    resources :events, only: [:show] do
      resources :event_attendees, only: [:create, :delete]
    end
    

    resources :users, only: [:show] do
        resources :events, except: [:show]
    end


    

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'
    has_many :event_attendees, dependent: :destroy
    has_many :attendees, through: :event_attendees, source: :attendee, dependent: :destroy

    validates :name, presence: true
    validates :description, presence: true
    validates :address, presence: true



    def user_attending?(user)
        self.attendees.include?(user)
    end


    scope :past_events, -> { where('date < ?', Time.now) }
    scope :upcoming_events, -> { where('date >= ?', Time.now) }


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def new
        @user = current_user
        @new_event = current_user.events_created.build

    end


    def create

        @user = current_user
        @new_event = current_user.events_created.build(event_params)

        if @new_event.save
            flash[:notice] = "The event was created successfully"
            redirect_to :root

        else
            flash.now[:alert] = "Something went wrong. We couldn't create the event"
            render :new

        end


    end


    def edit
        @event = Event.find(params[:id])

    end


    def update
        @event = Event.find(params[:id])
        
        if @event.update(event_params)
            flash[:notice] = "The event was editted successfully"
            redirect_to user_events_path(current_user)

        else
            flash.now[:alert] = "Something went wrong. We couldn't edit the event"
            render :edit

        end
        
    end



    def destroy
        @event = Event.find(params[:id])
        
        if @event.destroy
            redirect_to user_events_path(current_user.id), notice: "Event deleted succesfully"

        else
            redirect_to user_events_path(current_user.id), alert: "Couldnt delete the event"

        end
       
    end



    def show
        @event = Event.find(params[:id])
    end



    def index
        @all_events = Event.all

    end




    private


    def event_params

        params.require(:event).permit(:date, :name, :description, :address)

    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_show-list-attendees.html.erb
<div class="container">
    
    
    <% attendees_list.each do |attendee| %>
    
        <div class= "custom-card-main ">
    
            <div class="custom-card-main__title">
                <%= attendee.user_name%>
            </div>
    
            <div class="custom-card-main__stats">
                <div class= "custom-card-main__stats__item">
                    Registered at: <%= attendee.created_at.strftime('%Y-%m-%d') %>
                </div>
    
            </div>
    
        </div>
    <% end %>
    
</div>

app/views/events/edit.html.erb
<div class="container-fluid d-flex justify-content-center">
  <div class="custom-card">
    <div class="custom-card__title">
      <h2>Edit Event</h2>
    </div>
  
    <div class="custom-card__body w-">
  
      <%= form_with model: [current_user, @event] do |f| %>

       <div class="custom-card__body__field">
          <div class="card__label"><%= f.label :name %></div>
          <div class="card__field"><%= f.text_field :name %></div>
        </div>

        <div class="custom-card__body__field">
          <div class="card__label"><%= f.label :date %></div>
          <div class="card__field"><%= f.date_field :date %></div>
        </div>
       

        <div class="custom-card__body__field">
          <div class="card__label"><%= f.label :description %></div>
          <div class="card__field"><%= f.text_area :description %></div>
        </div>


         <div class="custom-card__body__field">
          <div class="card__label"><%= f.label :address %></div>
          <div class="card__field"><%= f.text_area :address %></div>
        </div>
       
          
        <div class="custom-card__body__actions">
          <%= f.submit "Update" %>
        </div>
        
      <% end %>
  
    </div>
    
  </div>
</div>

app/views/events/index.html.erb
<div class="container-fluid w-50 mt-5">

    <h1 class= "text-center mb-5">All events</h1>
   
    
    <div class="container custom-main-cards-container">
            <%= render partial: "users/event-preview", locals: {list_of_events: @all_events} %> <br>
    </div>


</div>

app/views/events/new.html.erb
<div class="container-fluid d-flex justify-content-center">
  <div class="custom-card">
    <div class="custom-card__title">
      <h2>Create New Event</h2>
    </div>
  
    <div class="custom-card__body">
  
      <%= form_with model: [@user, @new_event] do |f| %>
        <div class="custom-card__body__field">
          <div class="card__label"><%= f.label :date %></div>
          <div class="card__field"><%= f.date_field :date %></div>
        </div>
       
    
        <div class="custom-card__body__actions">
          <%= f.submit "Create Event" %>
        </div>
        
      <% end %>
  
    </div>
    
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid ">

    <div class="container-fluid w-75">


        <div class="row d-flex justify-content-between">

            <%= @event.date.strftime("%A, %d of %B")%>
            <h1 class="mt-3"><%= @event.name%></h1>
               
            <div class="col">


            <div class="row mt-5">
                    <div class="col">
                    <h2>About this event</h2>
                       <%= simple_format(@event.description) %>
                    </div>
                </div>



            <div class="row mt-5">
                    <div class="col">
                    <h2>Date and hour</h2>
                       <%= @event.date%>
                    </div>
                </div>


              <div class="row mt-5">
                    <div class="col">
                      <h2>Place</h2>
                       <%= simple_format(@event.address) %>
                    </div>
                </div>


                    <div class="row mt-5">
                    <div class="col">
                      <h2>Who is coming to this event?</h2>
                       
                        <%= render partial: "show-list-attendees", locals: {attendees_list: @event.attendees}%>

                    </div>
                </div>




            </div>




            <div class="col mt-5 d-flex justify-content-center">


            <div class="div sticky-top h-25 w-25">

                <div class="event-custom-card-attend">
                    <div class="event-custom-card-attend__title">
                        <h5>Do you want to come?</h5>
                    </div>
                    <div class="event-custom-card-attend__action">
                    <%= button_to "Attend", event_event_attendees_path(@event)%>
                    </div>
                </div>

            </div>
            
            
            
            
            </div>

        </div>





</div>